### Login as Company
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email" : "admin@jobfinder.com",
  "password" : "12345678"
}

### Login as Candidate
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email" : "20020376@vnu.edu.vn",
  "password" : "12345678"
}

### Confirm user
POST http://localhost:5000/api/register/confirm
Content-Type: application/json

{
  "email" : "nguyendanghoangdao11a@gmail.com",
  "confirmationKey" : "862235"
}

### Send email confirmation
GET http://localhost:5000/api/register/confirm/resend?email=nguyendanghoangdao11a@gmail.com